import {
  AlertCircle,
  Baby,
  Banknote,
  Bike,
  BookOpen,
  Briefcase,
  Bus,
  Car,
  Cat,
  Coffee,
  CreditCard,
  Dumbbell,
  Film,
  Flame,
  Gamepad2,
  Gift,
  GraduationCap,
  Heart,
  HeartPulse,
  Home,
  Laptop,
  Lightbulb,
  Music,
  PawPrint,
  PiggyBank,
  Plane,
  Receipt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Stethoscope,
  Tag,
  TrendingUp,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
  type LucideIcon,
} from 'lucide-react'

export const ICON_MAP: Record<string, LucideIcon> = {
  'alert-circle': AlertCircle,
  baby: Baby,
  banknote: Banknote,
  bike: Bike,
  'book-open': BookOpen,
  briefcase: Briefcase,
  bus: Bus,
  car: Car,
  cat: Cat,
  coffee: Coffee,
  'credit-card': CreditCard,
  dumbbell: Dumbbell,
  film: Film,
  flame: Flame,
  'gamepad-2': Gamepad2,
  gift: Gift,
  'graduation-cap': GraduationCap,
  heart: Heart,
  'heart-pulse': HeartPulse,
  home: Home,
  laptop: Laptop,
  lightbulb: Lightbulb,
  music: Music,
  'paw-print': PawPrint,
  'piggy-bank': PiggyBank,
  plane: Plane,
  receipt: Receipt,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  smartphone: Smartphone,
  sparkles: Sparkles,
  stethoscope: Stethoscope,
  tag: Tag,
  'trending-up': TrendingUp,
  utensils: Utensils,
  wallet: Wallet,
  wifi: Wifi,
  wrench: Wrench,
}

export const ICON_OPTIONS = Object.keys(ICON_MAP).sort()

export function getIcon(name: string | undefined | null): LucideIcon {
  if (!name) return Tag
  return ICON_MAP[name] ?? Tag
}
